version: '3.7'

services:
  app:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3005
    environment:
      - APPNAME=6c7748bd0ad3fbdff996e81581ad64d6